name: NetBattleRoyal
version: '1.0-SNAPSHOT'
author: anblusis
main: io.github.anblusis.netBattleRoyal.main.NetBattleRoyal
api-version: '1.20'
libraries:
  - io.github.monun:kommand-core:3.1.7
  - io.github.monun:tap-core:4.9.8
  - io.github.monun:invfx-core:3.3.2

